table moedas
	lineageTag: 0f86cac0-37b1-4d51-9d1c-2b6eda98550c

	column Moeda
		dataType: string
		lineageTag: 73052732-67e6-4845-a3b8-ea9d7edceea2
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: a6efd5ea-fa88-4e2d-b0e0-12f8bf6f8f5d
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		lineageTag: cb6f1078-2358-4ec1-8498-936d5941fca5
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition moedas = m
		mode: import
		queryGroup: Dimensões
		source = ```
				let
				    source = Table.FromRows(
				        {
				            {"BRL", "Real brasileiro", "R$ #,##0.00;R$ #,##0.00;-"},
				            {"AUD", "Dólar australiano", "$ #,##0.00;$ #,##0.00;-"},
				            {"CAD", "Dólar canadense", "$ #,##0.00;$ #,##0.00;-"},
				            {"CHF", "Franco suíço", "Fr #,##0.00;Fr #,##0.00;-"},
				            {"DKK", "Coroa dinamarquesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"EUR", "Euro", "€ #,##0.00;€ #,##0.00;-"},
				            {"GBP", "Libra Esterlina", "£ #,##0.00;£ #,##0.00;-"},
				            {"JPY", "Iene", "¥ #,##0;¥ #,##0;-"},
				            {"NOK", "Coroa norueguesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"SEK", "Coroa sueca", "kr #,##0.00;kr #,##0.00;-"},
				            {"USD", "Dólar dos Estados Unidos", "$ #,##0.00;$ #,##0.00;-"}
				        },
				        {"Moeda", "Nome", "Formato"}
				    ),
				    
				    changedType = Table.TransformColumnTypes(
				        source,{
				            {"Moeda", type text}, 
				            {"Nome", type text}, 
				            {"Formato", type text}
				        }
				    )
				
				in
				    changedType
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

